# This file is machine-generated - editing it directly is not advised

[[ArrayTools]]
git-tree-sha1 = "133bc65cb1241014956be71aaae9bb309519a1a3"
repo-rev = "master"
repo-url = "https://github.com/emmt/ArrayTools.jl"
uuid = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
version = "0.2.1"

[[InterpolationKernels]]
git-tree-sha1 = "1612c15fc902293d1232c93924740f54edc88c6c"
repo-rev = "master"
repo-url = "https://github.com/emmt/InterpolationKernels.jl"
uuid = "16730964-a2ec-11e9-36fa-47a4f82bfac6"
version = "0.2.0"
